package com.br4dev.imob.negocio.dto;

public enum TipoComercialDTO implements DTO{

	NAO_APLICA, CONSULTORIO, EDIFICIO_RESIDENCIAL, SALA_COMERCIAL, FAZENDA_SITIO, GALPAO, DEPOSITO, ARMAZEM, IMOVEL_COMERCIAL, LOJA, LOTE_TERRENO;

}
