package com.br4dev.imob.negocio.dto;

public enum TipoResidencialDTO implements DTO{

	NAO_APLICACA, APARTAMENTO_PADRAO, APARTAMENTO_DUPLEX, APARTAMENTO_TRIPLEX, APARTAMENTO_GIARDINO_GARDEN, APARTAMENTO_STUDIO, APARTAMENTO_LOFT, APARTAMENTO_KITNET, CASA_PADRAO, CASA_CONDOMINIO, LOTE_TERRENO;

}
